#!/bin/bash 
#SBATCH -n 32 #Number of cores 
#SBATCH -t 100:00:00 #Runtime in minutes
#SBATCH -p general #Partition to submit to
#SBATCH -D /n/home12/fjiang/semifrailty/trunk/semifrailty/code
#SBATCH -o /n/home12/fjiang/cluster/estimation.out
#SBATCH -e /n/home12/fjiang/cluster/estimation.error
#SBATCH -J estimation
#SBATCH --ntasks-per-node=32
#SBATCH --mem-per-cpu=1000 #Memory per cpu in MB (see also --mem)

R CMD BATCH --no-save --slave --quiet estimation.r
